# Generated by Django 2.2.6 on 2022-06-09 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='susbtitle',
            new_name='subtitle',
        ),
    ]
